"""adiciona coluna RG  em usuarios

Revision ID: c74163446482
Revises: 98e7c6c6df6b
Create Date: 2026-09-17 19:16:01.912259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74163446482'
down_revision: Union[str, Sequence[str], None] = '98e7c6c6df6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nr_rg', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nr_rg')
    # ### end Alembic commands ###
